### PR TITLE
Add auto-update feature and improve code

### PR DESCRIPTION
**Pull request by xilopaint**
• Add auto update capability using OneUpdater
• Refactor workflowHandler.sh by using Alfred's environment variables
• Fix Shellcheck issues
• Minor changes in README

### CODE REVIEW

**Comment by xilopaint** [comment]
In order to make the auto-update feature work you have to make a new release with the tag v1.1.

**Comment by mrodalgaard** [comment]
@xilopaint this looks really good. There is however still a failing unit test.

**Comment by xilopaint** [comment]
Sorry! I forgot to run the unit tests. Now everything is ok.

Also, I added support DNS.WATCH and Cloudflare DNS servers.

**Comment by mrodalgaard** [comment]
Great job. I will push to a new release. Thank you.

**Comment by xilopaint** [comment]
> Great job. I will push to a new release. Thank you.

There's an error in release notes. The new auto-update method doesn't depend on Packal. [OneUpdater](https://github.com/vitorgalvao/alfred-workflows/tree/master/OneUpdater) is a totally separate solution. Packal is no longer maintained and doesn't work for updates anymore.

**Pull request merged**
