### PR TITLE
VPN fix for MacOS Mojave fixes #4

### LINKED ISSUE #4: VPN list is not showing names and cannot connect

### PR DESCRIPTION
**Pull request by jpuris**

### CODE REVIEW

**Comment by mrodalgaard** [comment]
Thank you @jpuris . This looks great! Sorry for the late merge.

**Comment by xilopaint** [comment]
@mrodalgaard would it be possible to make a new release with this fix?

**Comment by mrodalgaard** [comment]
@xilopaint I will test and make a release very soon :)

**Comment by mrodalgaard** [comment]
A new version has been put on https://github.com/mrodalgaard/alfred-network-workflow/releases

**Pull request merged**
