### PR TITLE
Removing OneUpdater for Alfred Gallery

### PR DESCRIPTION
**Pull request by vitorgalvao**
When [the Alfred Gallery](https://www.alfredforum.com/topic/19058-submitting-workflows-for-the-alfred-gallery/) is live, added workflows will be updatable from within Alfred itself. As part of that, a prerequisite for inclusion will be that workflows *not* auto-update themselves. This is to avoid a confusing interaction of crossed updates *and* for security reasons, as Gallery workflows go through a number of checks.

Your development process won’t change. You’ll still make GitHub releases as usual to update the workflow. We’ll detect when new releases are out and queue them up for a new review and update in the Gallery.

This PR removes OneUpdater (and updates the info.plist, as it seems the file in the repo was behind the release). Merging it now and making a new release helps to speed up the process, but if you prefer to wait I’ll ping you again once the Gallery is live. It’s also fine if you prefer to close the PR and do the change yourself.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for the merge, @mrodalgaard. [The Gallery is now in early access](https://www.alfredapp.com/blog/releases/alfred-gallery-now-in-early-access/), so if you make a release we can get this in.

**Comment by vitorgalvao** [comment]
@mrodalgaard Just to let you know [the Gallery page is ready](https://alfred.app/workflows/mrodalgaard/network/), just waiting on the new release to make it live and make the download functional. If you ping me here after the release is done, we’ll take it from there.

Happy holidays!

**Comment by mrodalgaard** [comment]
Ping @vitorgalvao . Release 1.6.0 is published and ready for Alfred Gallery.

**Comment by vitorgalvao** [comment]
Thank you for the ping. Preparing the update, will be live soon.

**Pull request merged**
